# Generated by Django 4.0.2 on 2022-12-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='national_number',
            new_name='national_code',
        ),
    ]
