# Generated by Django 4.0.2 on 2023-01-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mega_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mega',
        ),
    ]
