# Generated by Django 4.0.2 on 2023-01-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_mega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
    ]
